### ISSUE TITLE
Remove sevice message "User joined group" after user kicked

### ISSUE THREAD

**Issue by benyaming** [benyaming/tg_admin_bot#4]
When user was kicked from chat, there is a service message "{user} join group" that looks stupid. Need to remove it with bot's messages.

**Comment by Asgoret** [comment]
Mb delete all service messages?

**Comment by benyaming** [comment]
> Mb delete all service messages?

In case of real user that had passed the check, chat members want to know that new person joined the chat. So it need only in case with bots/spammers.
